# Project information
site_name: IA Lefebvre Sarrut's Engineering Blog
site_url: https://www.lefebvre-sarrut.eu/research/ai/blog
site_author: Lefebvre Sarrut
site_description: >-
  Lefebvre Sarrut's AI research publication blog

# Copyright
copyright: Copyright &copy; 2022-2023 Lefebvre Sarrut

# Configuration
theme:
  name: material

  palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: white
        # accent: deep purple

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        # accent: deep purple

  font:
    text: OpenSans
    code: Roboto Mono

  icon:
    # repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - search.share

    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer

    - toc.follow

# Plugins
plugins:
  - blog:
      blog_dir: . # defined as standalone blog.

      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_readtime: true

      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"

      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_toc: false
      categories_allowed:
        - General
        - Performance
        - Optimization
        - LLM

      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_template: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: false

      authors: true
      authors_file: .authors.yml

  - search
  - tags

# Customization
extra:
  generator: false  # remove "made with material for mkdocs" notice.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/reddit
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/medium
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter

# Page tree
nav:
  - index.md  # defined as standalone blog.