# Project information
site_name: Lefebvre Sarrut's AI blog
site_url: https://www.ai.lefebvre-sarrut.eu
site_author: Lefebvre Sarrut
site_description: >-
  A blog fully dedicated to AI at Lefebvre Sarrut

# Copyright
copyright: Copyright &copy; 2022-2023 <a href="https://www.lefebvre-sarrut.eu/" target="_blank" rel="noopener">➜ Lefebvre Sarrut</a>

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/favicon.png

  palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-4
          name: Switch to dark mode
        primary: white
        accent: deep purple

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-7
          name: Switch to light mode
        primary: deep purple # old: black
        accent: deep purple

  font:
    text: Quicksand # Fredoka | Lexend | Lexend Deca | Outfit | Quicksand | Questrial | Poppins
    code: Roboto Mono

  icon:
     logo: lefebvre-sarrut/logo

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer

    - search.suggest
    - search.highlight
    - search.share

    - toc.follow

    - content.code.copy # code copy button enabled globally
    - content.code.annotate # code annotations enabled globally
    - content.tabs.link
    - content.tooltips

# Plugins
plugins:

  - blog:
      blog_dir: . # defined as standalone blog.

      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_readtime: true

      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"

      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_toc: false
      categories_allowed:
        - Benchmarking
        - Kernl
        - Machine Learning
        - Optimization
        - Transformer-Deploy
        - Transformers

      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_template: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: false

      authors: true
      authors_file: .authors.yml

      draft: false  # drafts are not published
      draft_on_serve: true # drafts are previewable
      draft_if_future_date: false

  - tags:
      tags_file: tags.md
      tags_allowed:
        - Bert
        - Cuda
        - GPU Quantization
        - Hugging Face
        - Kernel
        - Nvidia Triton
        - ONNX Runtime
        - OpenAI Triton
        - T5
        - TensorRT
        - TorchDynamo

  - typeset # preserves html formatting in the navigation and t.o.c
  - search
  - glightbox # image zoom functionality plugin

  - privacy:
      # external_links: true # github action > Unrecognised configuration name: external_links
      external_links_attr_map:
        target: _blank
      external_links_noopener: true

# Customization
extra:
  generator: false  # remove "made with material for mkdocs" notice.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LefebvreSarrut
      name: Lefebvre Sarrut on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://fr.linkedin.com/company/els-group
      name: Lefebvre Sarrut on Linkedin
    - icon: simple/maildotru
      link: mailto:rd-feedback@lefebvre-sarrut.eu
      name: Contact us


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.arithmatex:
      generic: true

# Page tree
nav:
  - index.md  # defined as standalone blog.
  # - Tags: tags.md # if you want an entry in the navigation