mbenesty:
  name: Michaël Benesty
  description: Head of Lefebvre Sarrut R&D, Former tax lawyer (Deloitte)
  avatar: https://avatars.githubusercontent.com/u/1029874?v=4

vmaugeri:
  name: Véronique Maugeri
  description: Product Manager R&D at Lefebvre Sarrut
  avatar: https://avatars.githubusercontent.com/u/60510634?v=4